//
//  UIControl+PANUIControlShorthand.h
//  Panopticon
//
//  Created by Pierre Houston on 2016-01-07.
//  Copyright © 2016 Pierre Houston. All rights reserved.
//
//  Generated by script generate_shorthand_headers.rb
//

#import <UIKit/UIKit.h>
#import "PANUIControlObservation.h"

PAN_ASSUME_NONNULL_BEGIN


@interface UIControl (PANUIControlShorthand)

#pragma mark - Observe touch-up-inside events

/**
 *  Observe touch-up-inside events by the receiver.
 *
 *  Details about the event that triggered the observation can be found within the `event` properties of the
 *  observation when the block is called.
 *
 *  The observation will automatically be stopped when either the control is deallocated.
 *
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observePressInitiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observePressWithBlock:(PANAnonymousObservationBlock)block;

/**
 *  Observe touch-up-inside events by the receiver, calling its block on the given operation queue.
 *
 *  Variation on `observePress[InitiallyPaused:]withBlock:` that adds an operation queue parameter. See the
 *  description for that method.
 *
 *  @param queue  The operation queue on which to call `block`.
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observePressOnQueue:(NSOperationQueue *)queue initiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observePressOnQueue:(NSOperationQueue *)queue withBlock:(PANAnonymousObservationBlock)block;

/**
 *  Observe touch-up-inside events by the receiver, calling its block on the given Grand Central Dispatch queue.
 *
 *  Variation on `observePress[InitiallyPaused:]withBlock:` that adds a GCD queue parameter. See the description for
 *  that method.
 *
 *  @param queue  The GCD queue on which to call `block`.
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observePressOnGCDQueue:(dispatch_queue_t)queue initiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observePressOnGCDQueue:(dispatch_queue_t)queue withBlock:(PANAnonymousObservationBlock)block;


/**
 *  Stop observing touch-up-inside events by the receiver.
 *
 *  Call on the same control on which you called one of the `observe..` methods above. Use to stop observing sometime
 *  before the control is deallocated. Alternately, can save the observation object returned from `observe..`,
 *  and call its `remove` method.
 *
 *  @return `YES` if the receiver was previously observing value-changed events from the receiver, `NO` otherwise.
 */
- (BOOL)stopObservingForPress;


#pragma mark - Observe value-changed events

/**
 *  Observe value-changed events by the receiver.
 *
 *  Details about the event that triggered the observation can be found within the `event` properties of the
 *  observation when the block is called.
 *
 *  The observation will automatically be stopped when either the control is deallocated.
 *
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observeValueInitiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observeValueWithBlock:(PANAnonymousObservationBlock)block;

/**
 *  Observe value-changed events by the receiver, calling its block on the given operation queue.
 *
 *  Variation on `observeValue[InitiallyPaused:]withBlock:` that adds an operation queue parameter. See the
 *  description for that method.
 *
 *  @param queue  The operation queue on which to call `block`.
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observeValueOnQueue:(NSOperationQueue *)queue initiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observeValueOnQueue:(NSOperationQueue *)queue withBlock:(PANAnonymousObservationBlock)block;

/**
 *  Observe value-changed events by the receiver, calling its block on the given Grand Central Dispatch queue.
 *
 *  Variation on `observeValue[InitiallyPaused:]withBlock:` that adds a GCD queue parameter. See the description
 *  for that method.
 *
 *  @param queue  The GCD queue on which to call `block`.
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observeValueOnGCDQueue:(dispatch_queue_t)queue initiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observeValueOnGCDQueue:(dispatch_queue_t)queue withBlock:(PANAnonymousObservationBlock)block;


/**
 *  Stop observing value-changed events by the receiver.
 *
 *  Call on the same control on which you called one of the `observe..` methods above. Use to stop observing sometime
 *  before the control is deallocated. Alternately, can save the observation object returned from `observe..`,
 *  and call its `remove` method.
 *
 *  @return `YES` if the receiver was previously observing value-changed events from the receiver, `NO` otherwise.
 */
- (BOOL)stopObservingForValue;


#pragma mark - Observe any events

/**
 *  Observe any events by the receiver
 *
 *  Details about the event that triggered the observation can be found within the `event` properties of the
 *  observation when the block is called.
 *
 *  The observation will automatically be stopped when either the control is deallocated.
 *
 *  @param events A bitmask of the events to observe.
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observeEvents:(UIControlEvents)events initiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observeEvents:(UIControlEvents)events withBlock:(PANAnonymousObservationBlock)block;

/**
 *  Observe any events by the receiver, calling its block on the given operation queue.
 *
 *  Variation on `observeEvents:[initiallyPaused:]withBlock:` that adds an operation queue parameter. See the
 *  description for that method.
 *
 *  @param events A bitmask of the events to observe.
 *  @param queue  The operation queue on which to call `block`.
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observeEvents:(UIControlEvents)events onQueue:(NSOperationQueue *)queue initiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observeEvents:(UIControlEvents)events onQueue:(NSOperationQueue *)queue withBlock:(PANAnonymousObservationBlock)block;

/**
 *  Observe any events by the receiver, calling its block on the given Grand Central Dispatch queue.
 *
 *  Variation on `observeEvents:[initiallyPaused:]withBlock:` that adds a GCD queue parameter. See the description
 *  for that method.
 *
 *  @param events A bitmask of the events to observe.
 *  @param queue  The GCD queue on which to call `block`.
 *  @param paused Observation is created with calls to the block paused, if `YES` then `collated` flag is also initially
 *                set to `YES`. Default is `NO` if parameter is omitted.
 *  @param block  The block to call when the key path observation is triggered, is passed the observation (same as the
 *                method result).
 *
 *  @return An observation object. You often don't need to keep this result.
 */
- (PAN_nullable PANUIControlObservation *)observeEvents:(UIControlEvents)events onGCDQueue:(dispatch_queue_t)queue initiallyPaused:(BOOL)paused withBlock:(PANAnonymousObservationBlock)block;

- (PAN_nullable PANUIControlObservation *)observeEvents:(UIControlEvents)events onGCDQueue:(dispatch_queue_t)queue withBlock:(PANAnonymousObservationBlock)block;


/**
 *  Stop observing artbitrary events by the receiver.
 *
 *  Call on the same control on which you called one of the `observe..` methods above. Use to stop observing sometime
 *  before the control is deallocated. Alternately, can save the observation object returned from `observe..`,
 *  and call its `remove` method.
 *
 *  @param events A bitmask of the events to stop observing. Must be equal to the bitmask passed to the corresponding
 *                `observe..` method.
 *
 *  @return `YES` if the receiver was previously observing value-changed events from the receiver, `NO` otherwise.
 */
- (BOOL)stopObservingForEvents:(UIControlEvents)events;

@end


PAN_ASSUME_NONNULL_END
